name: Update CS2 Stats

on:
  schedule:
    # Her g羹n T羹rkiye saatiyle 03:00 civar覺 癟al覺覺r (UTC 00:00)
    - cron: '0 0 * * *'
  # Manuel tetiklemek istersen "Run workflow" butonu 癟覺kar
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu ek (Checkout)
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ba覺ml覺l覺klar覺 Y羹kle
        run: |
          pip install requests python-dotenv

      - name: Scripti al覺t覺r
        env:
          # GitHub Secrets'tan API Key'i al覺p script'e iletiyoruz
          API_KEY: ${{ secrets.STEAM_API_KEY }}
        run: |
          # Scripti projenin ana dizininden 癟al覺t覺r覺yoruz
          python scripts/data-parse.py

      - name: Deiiklikleri Commit ve Push Et
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Deien veri dosyalar覺n覺 sahneye al (Stage)
          git add src/data.json scripts/baseline.json
          
          # Eer deiiklik varsa commit at ve pushla, yoksa hata verme
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update CS2 stats " && git push)